version: "3.8"
services:
  sensor1:
    build: .
    container_name: sensor1
    command: ["python", "-u", "src/sensor/sensor.py", "5000"]
    volumes:
      - ./src/sensor/snapshots:/app/src/sensor/snapshots
    ports:
      - "5000:5000"

  sensor2:
    build: .
    container_name: sensor2
    command: ["python", "-u", "src/sensor/sensor.py", "5001"]
    volumes:
      - ./src/sensor/snapshots:/app/src/sensor/snapshots
    ports:
      - "5001:5001"

  sensor3:
    build: .
    container_name: sensor3
    command: ["python", "-u", "src/sensor/sensor.py", "5002"]
    volumes:
      - ./src/sensor/snapshots:/app/src/sensor/snapshots
    ports:
      - "5002:5002"

  client:
    build: .
    container_name: client
    command: ["python", "-u", "src/client/client.py"]
    volumes:
      - ./src/client/snapshots:/app/src/client/snapshots
    depends_on:
      - sensor1
      - sensor2
      - sensor3

  monitor:
    build: .
    container_name: monitor
    command: ["python", "-u", "src/middleware/monitor_server.py"]
    ports:
      - "50051:50051"
