# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bully.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'bully.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ully.proto\x12\x05\x62ully\"$\n\x0f\x45lectionRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\"/\n\x10\x45lectionResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"1\n\x17\x43oordinatorNotification\x12\x16\n\x0e\x63oordinator_id\x18\x01 \x01(\t2\xa0\x01\n\x0c\x42ullyService\x12@\n\rStartElection\x12\x16.bully.ElectionRequest\x1a\x17.bully.ElectionResponse\x12N\n\x13\x41nnounceCoordinator\x12\x1e.bully.CoordinatorNotification\x1a\x17.bully.ElectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bully_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONREQUEST']._serialized_start=22
  _globals['_ELECTIONREQUEST']._serialized_end=58
  _globals['_ELECTIONRESPONSE']._serialized_start=60
  _globals['_ELECTIONRESPONSE']._serialized_end=107
  _globals['_COORDINATORNOTIFICATION']._serialized_start=109
  _globals['_COORDINATORNOTIFICATION']._serialized_end=158
  _globals['_BULLYSERVICE']._serialized_start=161
  _globals['_BULLYSERVICE']._serialized_end=321
# @@protoc_insertion_point(module_scope)
