# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bully_pb2 as bully__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bully_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BullyServiceStub(object):
    """Serviço Bully para comunicação entre sensores
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartElection = channel.unary_unary(
                '/bully.BullyService/StartElection',
                request_serializer=bully__pb2.ElectionRequest.SerializeToString,
                response_deserializer=bully__pb2.ElectionResponse.FromString,
                _registered_method=True)
        self.AnnounceCoordinator = channel.unary_unary(
                '/bully.BullyService/AnnounceCoordinator',
                request_serializer=bully__pb2.CoordinatorNotification.SerializeToString,
                response_deserializer=bully__pb2.ElectionResponse.FromString,
                _registered_method=True)


class BullyServiceServicer(object):
    """Serviço Bully para comunicação entre sensores
    """

    def StartElection(self, request, context):
        """Método para iniciar a eleição
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnounceCoordinator(self, request, context):
        """Método para anunciar o coordenador
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BullyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartElection': grpc.unary_unary_rpc_method_handler(
                    servicer.StartElection,
                    request_deserializer=bully__pb2.ElectionRequest.FromString,
                    response_serializer=bully__pb2.ElectionResponse.SerializeToString,
            ),
            'AnnounceCoordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceCoordinator,
                    request_deserializer=bully__pb2.CoordinatorNotification.FromString,
                    response_serializer=bully__pb2.ElectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bully.BullyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bully.BullyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BullyService(object):
    """Serviço Bully para comunicação entre sensores
    """

    @staticmethod
    def StartElection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bully.BullyService/StartElection',
            bully__pb2.ElectionRequest.SerializeToString,
            bully__pb2.ElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnnounceCoordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bully.BullyService/AnnounceCoordinator',
            bully__pb2.CoordinatorNotification.SerializeToString,
            bully__pb2.ElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
